import os
import re

from global_localization.base import LocalizationBase


class LocalizationNetVLADOnly(LocalizationBase):
    """Class for global localization methods according to the given map and queries with NetVLAD only."""

    def __init__(
        self,
        config,
        map_obs_dir,
        query_dir,
        binary_topdown_map=None,
        visualize=False,
    ):
        """Initialize localization instance with specific map & query image directories."""
        super().__init__(
            config,
            map_obs_dir,
            query_dir,
            binary_topdown_map=binary_topdown_map,
            visualize=visualize,
        )

        self.query_prefix = os.path.join(self.scene_dirname, self.query_dirname)
        self.hloc_result = self._load_hloc_result()

    def _load_hloc_result(self):
        """Load NetVLAD retrieval pair text file which is generated by hloc."""
        if self.test_on_sim:
            hloc_output_dir = os.path.join(self.config.PathConfig.HLOC_OUTPUT, self.scene_dirname, self.level)
        else:
            hloc_output_dir = os.path.join(self.config.PathConfig.HLOC_OUTPUT, self.scene_dirname)

        hloc_output_file = os.path.join(hloc_output_dir, "pairs-netvlad.txt")

        with open(hloc_output_file) as f:  # pylint: disable=unspecified-encoding
            retrieval_pairs = f.readlines()

        return retrieval_pairs

    def localize_with_observation(self, query_id: str):
        """Get global localization result according to query id input."""
        # Find pair texts from NetVLAD pair result according to query id
        high_simil_pair_list = []
        query = f"{self.query_prefix}/{query_id}"
        for pair in self.hloc_result:
            if query in pair:
                high_simil_pair_list.append(pair)

        # Get file name string from pair text
        max_pair = high_simil_pair_list[0]
        max_id_string = re.split("[. /]", max_pair)[-2]

        if "_" in max_id_string:  # If node has multiple observations, extract node id from file name string
            map_node_with_max_value = int(max_id_string.split("_")[0])
        else:
            map_node_with_max_value = int(max_id_string)

        high_similarity_set = []
        for high_pair in high_simil_pair_list:
            high_id_string = re.split("[. /]", high_pair)[-2]

            if "_" in high_id_string:  # If node has multiple observations, extract node id from file name string
                high_similarity_set.append(int(high_id_string.split("_")[0]))
            else:
                high_similarity_set.append(int(high_id_string))

        return map_node_with_max_value, high_similarity_set
